package com.seal.hackathon.aireview.support;



import com.fasterxml.jackson.databind.JsonNode;

import com.seal.hackathon.aireview.entity.AiReview;

import java.util.ArrayList;

import java.util.List;

import org.springframework.util.StringUtils;



public final class AiReviewIssueFormatter {



    private AiReviewIssueFormatter() {}



    public static String buildTitle(String teamName, String commitShaShort) {

        return "[AI Auditor] Thay đổi quan trọng — " + teamName + " (" + commitShaShort + ")";

    }



    public static String buildBody(String teamName, String repoLabel, JsonNode perPushRoot, AiReview review) {

        StringBuilder body = new StringBuilder();

        body.append("## Báo cáo AI Auditor (tham khảo)\n\n");

        body.append("**Đội:** ").append(teamName).append("\n");

        body.append("**Repository:** `").append(repoLabel).append("`\n");

        if (StringUtils.hasText(review.getCommitSha())) {

            body.append("**Commit:** `").append(review.getCommitSha()).append("`\n");

        }

        body.append("\n> Đánh giá tự động — không phải điểm chính thức của ban tổ chức.\n\n");



        appendSection(body, "Tóm tắt push", textAt(perPushRoot, "overall_picture", "push_summary"));

        appendSection(body, "Dự án", textAt(perPushRoot, "overall_picture", "project_about"));

        appendSection(body, "RAG maturity", textAt(perPushRoot, "rag_maturity", "level"));

        appendSection(body, "Ưu điểm", textAt(perPushRoot, "assessment", "advantages"));

        appendSection(body, "Nhược điểm", textAt(perPushRoot, "assessment", "disadvantages"));

        appendSection(body, "Bảo mật", textAt(perPushRoot, "assessment", "security"));

        appendSection(body, "Cải thiện", textAt(perPushRoot, "assessment", "improvement_areas"));



        appendListSection(body, "Gợi ý test case", perPushRoot.path("suggested_test_cases"));

        appendListSection(body, "Câu hỏi phản biện cho BGK", perPushRoot.path("suggested_questions_for_team"));



        body.append("\n---\n*Generated by Hackathon AI Review*\n");

        return body.toString();

    }



    private static void appendSection(StringBuilder body, String title, String content) {

        if (!StringUtils.hasText(content)) {

            return;

        }

        body.append("### ").append(title).append("\n\n");

        body.append(content.trim()).append("\n\n");

    }



    private static void appendListSection(StringBuilder body, String title, JsonNode arrayNode) {

        if (!arrayNode.isArray() || arrayNode.isEmpty()) {

            return;

        }

        List<String> items = new ArrayList<>();

        arrayNode.forEach(node -> {

            if (node.isTextual() && StringUtils.hasText(node.asText())) {

                items.add(node.asText().trim());

            }

        });

        if (items.isEmpty()) {

            return;

        }

        body.append("### ").append(title).append("\n\n");

        for (String item : items) {

            body.append("- ").append(item).append("\n");

        }

        body.append("\n");

    }



    private static String textAt(JsonNode root, String objectField, String textField) {

        JsonNode value = root.path(objectField).path(textField);

        return value.isTextual() ? value.asText() : null;

    }

}
